// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// File is the golang structure of table file for DAO operations like Where/Data.
type File struct {
	g.Meta   `orm:"table:file, do:true"`
	Id       interface{} //
	Name     interface{} //
	Hash     interface{} //
	Fsize    interface{} //
	PutTime  interface{} //
	MineType interface{} //
	Butket   interface{} //
}
