// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// File is the golang structure for table file.
type File struct {
	Id       int    `json:"id"       ` //
	Name     string `json:"name"     ` //
	Hash     string `json:"hash"     ` //
	Fsize    int    `json:"fsize"    ` //
	PutTime  int    `json:"putTime"  ` //
	MineType string `json:"mineType" ` //
	Butket   string `json:"butket"   ` //
}
